### ISSUE TITLE
Relayer volume in "Top Relayers" skewed?..

### ISSUE THREAD

**Issue by veox** [0xTracker/0x-tracker-client#141]
Some relayers in the current top 5 - e.g. DDEX, Paradex, possibly STAR BIT - act as a middle-man between parties in trades, creating an order with themselves to match both sides (on-chain).

For example, here is Paradex:

* [taking my side of the order](https://0xtracker.com/fills/5c071172704d000004995fa9);
* [passing it along to the other side](https://0xtracker.com/fills/5c071172704d000004995faa).

(Fee recipient is set to `0x00..00`.)

This was a single trade where an equivalent of ~71.975 USD changed hands, but the two fills contribute ~143.95 USD to Paradex's volume ticker.

Paradex is (probably) doing this to lift the requirement of maker needing unwrapped ether; and also to have a tighter control on transaction fees - both sides need only provide a signed message.

In the "Recent Fills" list, these fills (understandably) appear in pairs.

-----

Here's an example of a [fill via RadarRelay](https://0xtracker.com/fills/5c06e38b704d000004995cba), which doesn't seem to be doing this (at least yet). Sides are matched atomically, fee recipient is set to RR's account address.

-----

Or is this operational difference covered in `0xtracker`, and I simply can't find it?..

**Comment by cbovis** [comment]
Hi @veox thanks for the question! Apologies for the late response.

There are a couple of different volume metrics used on the site; Network Volume and Trading Volume. Most of the metrics on display are Network Volume which is the total of all exchanges facilitated by the protocol. The top relayers list however is based on Trading Volume, this factors in the two sides of each trade for relayers such as DDEX and Paradex. 

The calculation of trading volume is pretty crude but does the job for now. If you look in https://github.com/0xTracker/0x-tracker-api/blob/master/src/stats/get-relayer-stats.js you'll be able to see near the end of the file that volume for a number of relayers is halved.

I can understand this being somewhat confusing and am hoping to iterate on it in the future with clearer messaging on the site around what certain figures represent.

**Comment by veox** [comment]
Indeed!..

Thank you for linking the particular file; I should have simply searched for a name of a relayer where I suspected (incorrectly) that this was happening.

**Comment by cbovis** [comment]
All good 😄  closing this one down!
