### ISSUE TITLE
Project setup 

### ISSUE THREAD

**Issue by vnallamhawk** [0xTracker/0x-tracker-client#198]
Hi Team,

I am facing the following issue while doing the code setup. I have ran the following commands in my terminal npm install and npm run start

Error: val is not a non-empty string or a valid number. val=undefined
./node_modules/ms/index.js.module.exports
./node_modules/ms/index.js:34
setTimer
./src/features/auto-reload/configure.js:10
   7 |   timer = setTimeout(() => {
   8 |     store.dispatch.autoReload.trigger();
   9 |     setTimer(store);
> 10 |   }, ms(process.env.REACT_APP_AUTO_RELOAD_INTERVAL));
  11 | };
  12 | 

Could you please help.

**Comment by cbovis** [comment]
Hi @vnallamhawk, you'll need to run `cp .env.example .env` from the Getting Started section of README. Ideally the app should work without that setup step so I'll look into making the environment variables optional. Thanks for pointing it out!

**Comment by vnallamhawk** [comment]
hello @cbovis . it fixed the issue. thanks. the above command clones a file called .env from .env.example right

**Comment by cbovis** [comment]
Yep that’s correct 👍

Closing the issue, thanks 🙂
