### ISSUE TITLE
Add VeriSafe as relay and token

### ISSUE THREAD

**Issue by JoaoCampos89** [0xTracker/0x-tracker-client#510]
Hi 0x-tracker team!

We released a 0x based dex today at: https://dex.verisafe.io/#/erc20

What are the steps to add VeriSafe token and relay to the tracker? I could do a pull request or leave here all the data needed. Relayer is at this fee recipient address: 
https://0xtracker.com/search?q=0x5265bde27f57e738be6c1f6ab3544e82cdc92a8f
VSF token: https://etherscan.io/token/0xac9ce326e95f51b5005e9fe1dd8085a01f18450c

**Comment by cbovis** [comment]
VeriDEX has now been added https://0xtracker.com/relayers/veridex
