### ISSUE TITLE
Implement react-helmet for page metadata

### ISSUE THREAD

**Issue by cbovis** [0xTracker/0x-tracker-client#66]
Currently we display the same metadata on all pages which isn't great for SEO and provides no hints to users who keep multiple 0x Tracker tabs open. Metadata should be configured on a per-page basis, react-helmet would be a good choice for implementing this.

https://github.com/nfl/react-helmet

**Comment by inqii** [comment]
Hey I will take this on! Im just starting out, but a friend of mine could help out if I need help.

**Comment by cbovis** [comment]
Closing this off as it’s now been completed!
