### ISSUE TITLE
Add filters to the fills page

### ISSUE THREAD

**Issue by cbovis** [0xTracker/0x-tracker-client#72]
The fills page at https://0xtracker.com/fills would be much more useful to people interested in exploring the data set if there were filters available. 

A good set of initial filters would be:

* Relayer(s)
* Protocol Version
* Token(s)
* Date Range

The API will need updating to support these options when fetching fills before this can be implemented.

## Design Inspiration
![filters](https://user-images.githubusercontent.com/34132/51024153-d27e6d00-15dc-11e9-9a36-02c49745756c.png)

**Comment by vnallamhawk** [comment]
@cbovis  : can i take this up ?

**Comment by cbovis** [comment]
Best to hold off on this one for now. A couple of things:

* 0x-tracker-api will need updating to support filtering of fills
* the client codebase is currently in flux (see #197), so its best to avoid any major feature development until #197 has been merged

**Comment by vnallamhawk** [comment]
When would 19 7 be merged ?

**Comment by cbovis** [comment]
#197 has been merged now so this is good to be worked on. First steps for this repository will be designing the filter component in Storybook. Once that has been completed and the API has been updated to support filters we’ll be able to wire them together.

On mobile right now but I’ll put together some more extensive requirements once I’m back on my laptop.

**Comment by vnallamhawk** [comment]
@cbovis : thanks for the update. Could you please help with the requirement. I am eagerly waiting for kickstarting on this. Thanks.

**Comment by cbovis** [comment]
Tracking of this issue has been moved to https://github.com/0xTracker/0x-tracker-client/issues/769 which has a number of sub-tasks associated with it.
