### ISSUE TITLE
Add option for Trade Volume (and Count) overtime charts to display weekly aggregated data

### ISSUE THREAD

**Issue by romainbutteaud** [0xTracker/0x-tracker-client#753]
**Problem:**
Since the data has high variance on a daily basis it's hard to visualize growth or trends.

**Solution:**
- Having the option to show the same chart but with weekly aggregated data would benefit user experience. 
- Use bar charts instead of area charts

**Comment by cbovis** [comment]
@romainbutteaud thanks for the suggestion. This is definitely something that I'm interested in implementing as I agree that it can be difficult to visualize trends over the year/all time periods.

**Comment by cbovis** [comment]
Weekly granularity has been implemented for 1y views of metrics. I plan to implement a UI for users to also specify their preferred granularity via a per-chart preferences dialog.

Closing in favor of Trello for feature/enhancement tracking: https://trello.com/b/4cY2eOsQ/0x-tracker-roadmap

**Comment by romainbutteaud** [comment]
Yes I saw thank awesome! 👍
