### ISSUE TITLE
Horizontally overflowed content in the sidebar

### ISSUE THREAD

**Issue by lesha1201** [0xTracker/0x-tracker-client#978]
The sidebar has an unintended horizontal scrollbar on a desktop.

![image](https://user-images.githubusercontent.com/10157660/89300003-390c2580-d670-11ea-8534-ad7e7321e2ea.png)

**Environment:**
- Chrome 84, Firefox 79/80

**Comment by cbovis** [comment]
Thanks @lesha1201. Is this in Windows? I can't replicate on macOS.

**Comment by lesha1201** [comment]
@cbovis Yes, it's on Windows 10 v2004. PWA's version should be the latest

**Comment by lesha1201** [comment]
@cbovis I think it's actually an issue in browsers that has width on scrollbars. As I know scrollbars on macOS doesn't take any space.
